### ISSUE TITLE
Import issues from Bugzilla

### ISSUE THREAD

**Issue by inexorabletash** [w3c/IndexedDB#15]
[Open](https://www.w3.org/Bugs/Public/buglist.cgi?product=WebAppsWG&amp;component=Indexed%20Database%20API&amp;bug_status=NEW&amp;bug_status=ASSIGNED&amp;bug_status=REOPENED):
* [x] [DOMStringList has been removed from DOM](https://www.w3.org/Bugs/Public/show_bug.cgi?id=28067) - imported as #28
* [x] [nested keyPath: allow specification which part should be iterated if it's an array](https://www.w3.org/Bugs/Public/show_bug.cgi?id=28456) - imported as #35
* [x] [Ability to get non-sequential records from various operations](https://www.w3.org/Bugs/Public/show_bug.cgi?id=16595) - imported as #19 
* [x] [[IndexedDB] Operations that raise multiple exceptions types should define order](https://www.w3.org/Bugs/Public/show_bug.cgi?id=17681) - imported as #11 
* [x] [IDBCursor should walk on secondary ordering of index value](https://www.w3.org/Bugs/Public/show_bug.cgi?id=20257) - imported as #14 
* [x] [Inform script of corruption-induced data loss](https://www.w3.org/Bugs/Public/show_bug.cgi?id=22370) - imported as #30
* [x] ~~[Support Binary Keys](https://www.w3.org/Bugs/Public/show_bug.cgi?id=23332) - imported as #21~~
* [x] [IDB exposes GC behavior](https://www.w3.org/Bugs/Public/show_bug.cgi?id=25223) - imported as #29
* [x] ~~[Remove DOMError from IDB](https://www.w3.org/Bugs/Public/show_bug.cgi?id=27727) - imported as #16~~

[Postponed:](https://www.w3.org/Bugs/Public/buglist.cgi?product=WebAppsWG&amp;component=Indexed%20Database%20API&amp;bug_status=RESOLVED&amp;resolution=LATER)
* [x] [We should add some form of dynamic transaction to IndexedDB](https://www.w3.org/Bugs/Public/show_bug.cgi?id=11528) - imported as #34
* [x] [IndexedDB: Add API for enumerating databases](https://www.w3.org/Bugs/Public/show_bug.cgi?id=16137) - imported as #31
* [x] [Remove NotSupportedError on creating index for multiEntry index with array keyPath](https://www.w3.org/Bugs/Public/show_bug.cgi?id=21836) - imported as #36
* [x] [Modification for IDBObjectStore's clear and delete method](https://www.w3.org/Bugs/Public/show_bug.cgi?id=22130) - imported as #32
* [x] [Allow expressions in addition to keyPaths when creating indexes](https://www.w3.org/Bugs/Public/show_bug.cgi?id=10000) - imported as #33

**Comment by inexorabletash** [comment]
All done!
